language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - pip install nose
script:
  - nosetests notify_send_tests.py --with-coverage --cover-package=notify_send --cover-erase
  - flake8 --ignore=E402,W504 --max-line-length=100 notify_send.py notify_send_tests.py
after_success:
  - coveralls
